// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQsF_U9GjJ2nKfbg6Tivneb4qYYu8gNsM',
    appId: '1:115910655017:web:83e5e185255e1765147038',
    messagingSenderId: '115910655017',
    projectId: 'chatapp-b793a',
    authDomain: 'chatapp-b793a.firebaseapp.com',
    storageBucket: 'chatapp-b793a.appspot.com',
    measurementId: 'G-ZPZNNX1941',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyYUuk18GiavfJEYN5QGZ7kLBNeBA4HxU',
    appId: '1:115910655017:android:18b9778cb73015bc147038',
    messagingSenderId: '115910655017',
    projectId: 'chatapp-b793a',
    storageBucket: 'chatapp-b793a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlygc46TVtksKlByW_IJm8nNPm_6tyU1k',
    appId: '1:115910655017:ios:bf7909e647e808fb147038',
    messagingSenderId: '115910655017',
    projectId: 'chatapp-b793a',
    storageBucket: 'chatapp-b793a.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlygc46TVtksKlByW_IJm8nNPm_6tyU1k',
    appId: '1:115910655017:ios:01e523d6d3a419b8147038',
    messagingSenderId: '115910655017',
    projectId: 'chatapp-b793a',
    storageBucket: 'chatapp-b793a.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
